### ISSUE TITLE
IF NOT EXISTS?

### ISSUE THREAD

**Issue by ArturFormella** [lacanoid/pgddl#10]
Is it possible to add IF NOT EXISTS to CREATE's?
Thanks! :)

**Comment by lacanoid** [comment]
Yes, of course.

I'm not sure if this is wanted in all cases though.
Do you have a particular use case in mind?

Also, older versions of postgres support IF NOT EXISTS in less places than newer ones.
Will it do, if this is for CREATE TABLE only? This is supported from 9.1 on.

**Comment by ArturFormella** [comment]
Ok, lets start with CREATE TABLE and CREATE FOREIGN TABLE, both available from 9.1 :)
I was thinking of state-based database development.

Example:

SELECT ddlx_create('my_table'::regclass, '{"table_if_not_exists": "true"}'::json);
or even:
SELECT ddlx_create('my_table'::regclass, true);

**Comment by lacanoid** [comment]
IF NOT EXISTS has been implemented in some places. One can use it by specifying 'ine' option:

    select ddlx_create('my_table'::regclass,'{ine}');
