### ISSUE TITLE
pgddl is now available as a RPM package

### ISSUE THREAD

**Issue by daamien** [lacanoid/pgddl#11]
Hi ! 

Just a quick note to say that this extension is now packaged as a RPM in the PostgreSQL official yum repository.

https://yum.postgresql.org/testing/12/redhat/rhel-7-x86_64/repoview/ddlx_12.html

Users can now install the extension with: 

```console
$ yum instal ddlx_11
```

where 11 is the version of the PostgreSQL instance.

**Comment by lacanoid** [comment]
Great! Thanks!
