### ISSUE TITLE
Schema diffs and column ordering

### ISSUE THREAD

**Issue by eradman** [lacanoid/pgddl#12]
I have been experimenting with the `ddlx` extension as a means of generating a schema diff between a test and a production database

```
psql $url_prod --no-psqlrc -At -c "SELECT ddlx_script('farmers'::regclass)" > farmers_1.out
psql $url_test --no-psqlrc -At -c "SELECT ddlx_script('farmers'::regclass)" > farmers_2.out
vimdiff -O *.out
```

The first difficulty I ran into is that column names are not sorted. Is this easy to do?

Also, what do you think of this use case for `ddlx_script`?

**Comment by lacanoid** [comment]
Seems like an interesting idea!

Columns are sorted by order in which they are defined (attnum) which seems a reasonable default.
It should work fine for diffs, unless you reorder columns. In this case it makes sense to show this in a diff.

What did you have in mind?

**Comment by eradman** [comment]
I normally define a schema in a series of text files

```
01-extensions.sql
02-functions.sql
03-tables.sql
04-partitions.sql
05-views.sql
06-permissions.sql
07-fixtures.sql
08-triggers.sql
```

Then before committing I'll run a script to apply these in order to an ephemeral database

```
url_test=$(pg_tmp)
for sql in `ls *.sql`; do
    psql $url_test -f $sql
done
```

This validates the basic validity of the schema, but it would be very helpful to be ale to compare this with a production database

```
psql $url -c 'CREATE EXTENSION ddlx'
for table in famers products; do
    psql $url_prod --no-psqlrc -At -c "SELECT ddlx_script('$table'::regclass)" > ${table}_1.out
    psql $url_test --no-psqlrc -At -c "SELECT ddlx_script('$table'::regclass)" > ${table}_2.out
done
```

Sometimes we even apply schema changes against a _staging_ database, then _production_, and all three of these (ephemeral, staging, production) now have different column ordering.
