### ISSUE TITLE
tag your releases

### ISSUE THREAD

**Issue by jm-g** [lacanoid/pgddl#15]
For people who want to reliably install a defined version of this extensions, it is really helpful to have a git tag corresponding to each version. The last version with a git tag is 0.5, whereas the latest release is 0.16.

Otherwise, thanks for a really helpful tool.

**Comment by lacanoid** [comment]
Hmm, interesting. How do I do this?

**Comment by jm-g** [comment]
> git tag -a 0.16 $COMMIT_ID_OF_RELEASE
> git push origin --tags

But, I guess you found that out yourself, since the tags are now present.
