### ISSUE TITLE
Add support for PostgreSQL 13

### ISSUE THREAD

**Issue by eradman** [lacanoid/pgddl#16]
For the most part the `ddlx` extension works, but there are a couple test failures

Here is the result on CentOS 7.7 with PostgreSQL 13beta3

$ make installcheck                                                                                                                                   
/usr/pgsql-13/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/pgsql-13/bin'    --inputdir=test --dbname=contrib_regression init manifest role type class fdw tsearch policy misc script pg13
(using postmaster on Unix socket, default port)
============== dropping database "contrib_regression" ==============
NOTICE:  database "contrib_regression" does not exist, skipping
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test init                         ... ok           71 ms
test manifest                     ... ok           34 ms
test role                         ... ok          100 ms
test type                         ... ok          415 ms
test class                        ... ok         2142 ms
test fdw                          ... ok          300 ms
test tsearch                      ... ok          256 ms
test policy                       ... ok          258 ms
test misc                         ... FAILED     1309 ms
test script                       ... ok          393 ms
test pg13                         ... /bin/sh: /tmp/pgddl/test/sql/pg13.sql: No such file or directory
diff: /tmp/pgddl/test/expected/pg13.out: No such file or directory
diff: /tmp/pgddl/results/pg13.out: No such file or directory
diff command failed with status 512: diff  "/tmp/pgddl/test/expected/pg13.out" "/tmp/pgddl/results/pg13.out" > "/tmp/pgddl/results/pg13.out.diff"
make: *** [installcheck] Error 2

**Comment by lacanoid** [comment]
Tnx!

Added missing pg13 files.
What is the issue with misc? Can you post regression.diff?

**Comment by eradman** [comment]
Excellent! Here's the regression with `test misc`. Everything else passes now

```diff
diff -U3 /tmp/pgddl/test/expected/misc.out /tmp/pgddl/results/misc.out
--- /tmp/pgddl/test/expected/misc.out   2020-09-10 15:20:35.249609000 -0400
+++ /tmp/pgddl/results/misc.out 2020-09-10 17:16:09.538377497 -0400
@@ -71,20 +71,15 @@
 (1 row)
 CREATE DEFAULT CONVERSION "ascii_to_utf8++"
   FOR 'SQL_ASCII' TO 'UTF8' FROM ascii_to_utf8;
+ERROR:  encoding conversion to or from "SQL_ASCII" is not supported
 COMMENT ON CONVERSION "ascii_to_utf8++" IS 'conversion++ for SQL_ASCII to UTF8';
+ERROR:  conversion "ascii_to_utf8++" does not exist
 select ddlx_create(oid) from pg_conversion where conname in ('ascii_to_utf8++') order by conname;
 ddlx_create
-CREATE DEFAULT CONVERSION "ascii_to_utf8++"
-  FOR 'SQL_ASCII' TO 'UTF8' FROM ascii_to_utf8;
-COMMENT ON CONVERSION "ascii_to_utf8++" IS 'conversion++ for SQL_ASCII to UTF8';
-ALTER CONVERSION "ascii_to_utf8++" OWNER TO postgres;
-
-(1 row)
+(0 rows)
 select ddlx_drop(oid) from pg_conversion where conname in ('ascii_to_utf8++') order by conname;
 ddlx_drop
-DROP CONVERSION "ascii_to_utf8++";
-
-(1 row)
+(0 rows)
 select ddlx_grants('test_class_r'::regclass::oid);
 ddlx_grants
 GRANT DELETE ON TABLE test_class_r TO postgres;
```

**Comment by lacanoid** [comment]
I changed encoding in failing test from SQL_ASCII to LATIN1. 
Perhaps this will work better.

**Comment by eradman** [comment]
This changed fixed the problem. All tests pass now with PG 13! Thanks again,
