### ISSUE TITLE
Proposal: exclude objects  from extensions in ddlx_get_dependants.  Maybe optionally

### ISSUE THREAD

**Issue by ayuryshev** [lacanoid/pgddl#19]
I encountered problem when I tried:

```sql
SELECT ddlx_script('public'::regnamespace);
```

In output script there are objects that comes from installed exensions 'postgis', 'pgcrypto','uud-ospp', 'dblink', etc.

With this query:

```sql
WITH objects_from_exts AS (
SELECT  
        D.objid,
        E.extname 
    FROM  
         pg_depend D
         JOIN pg_extension E on D.refclassid = 'pg_extension'::regclass
            and D.refobjid = E.oid
)         
SELECT  
        O.extname,I.sql_kind, I.sql_identifier
    FROM 
        ddlx_get_dependants('public'::regnamespace) D 
        JOIN objects_from_exts O  ON D.objid = O.objid,
        ddlx_identify(O.objid) I
```

I see:

![image](https://user-images.githubusercontent.com/604348/107464738-b914ca00-6b82-11eb-802c-4fcc94b4ffe4.png)

I propose to exclude those objects from  `ddlx_get_dependants`. Maybe as an option like `exclude_ext_objs bool DEFAULT true`

**Comment by lacanoid** [comment]
Still, the interplay of namespaces and extensions is and interesting one. The idea was to have pgddl export postgres contrib extensions correctly, which it now fails miserably.

This is perhaps a more reasonable default behaviour for namespaces and current behaviour should indeed be an option.

**Comment by lacanoid** [comment]
Excluding objects from extensions has been implemented.
