### ISSUE TITLE
Regression tests fail against v14

### ISSUE THREAD

**Issue by devrimgunduz** [lacanoid/pgddl#21]
Hi,

v14 beta1 is out. ddlx builds fiine, but regression tests fail. Logs are attached. Can you please take a look?

We started to build v14 RPMs, so a new release is appreciated.

Thanks!

Regards, Devrim

[regression.diffs-ddlx.txt](https://github.com/lacanoid/pgddl/files/6591831/regression.diffs-ddlx.txt)

**Comment by lacanoid** [comment]
Disabled the problematic test. 

If it builds ok, I can make a release.

**Comment by devrimgunduz** [comment]
Hi @lacanoid ,

Thanks! It works now. You can push a  new release.

Regards, Devrim

**Comment by lacanoid** [comment]
This has been released as 0.19
