### ISSUE TITLE
ENABLE REPLICA TRIGGER

### ISSUE THREAD

**Issue by PegoraroF10** [lacanoid/pgddl#26]
On ddlx_create_trigger function you have to see TG_ENABLED = 'R', something like
CREATE OR REPLACE FUNCTION ddlx_create_trigger(oid)
 RETURNS text LANGUAGE sql AS $function$
 select pg_get_triggerdef($1,true)||
        case t.tgenabled 
        when 'D'  then format(E';\nALTER TABLE %s DISABLE TRIGGER %I', cast(t.tgrelid::regclass as text), t.tgname)
        when 'R'  then format(E';\nALTER TABLE %s ENABLE REPLICA TRIGGER %I', cast(t.tgrelid::regclass as text), t.tgname)
        when 'A'  then format(E';\nALTER TABLE %s ENABLE ALWAYS TRIGGER %I', cast(t.tgrelid::regclass as text), t.tgname)
        else '' end||E';\n'
   from pg_trigger t
  where oid = $1
$function$  strict;

**Comment by lacanoid** [comment]
Great, thanks for these!!!
