### ISSUE TITLE
tests failing

### ISSUE THREAD

**Issue by rngadam** [lacanoid/pgddl#3]
```
============== running regression test queries        ==============
test init                     ... FAILED
test role                     ... ok
test type                     ... FAILED
test class                    ... FAILED
test fdw                      ... FAILED
test script                   ... FAILED
test misc                     ... FAILED
```

https://gist.github.com/rngadam/21af1c538d3ae48f05500699df3d5ce3

mostly seems to be due to different ownership.

**Comment by lacanoid** [comment]
Interesting...
Perhaps adding 'SET ROLE postgres' in tests would help with this.

Also, the sorting of functions in init seems different.
Which version of postgres and locale are you using?

Also, you don't seem to have user postgres?

**Comment by lacanoid** [comment]
I have improved regression tests to use postgres role.
This will hopefully fix the issue.
Thanks for the report.

**Comment by rngadam** [comment]
Note that the tests still fail on homebrew (MacOS X) install of postgresl 10 as it only creates a superuser with the account installing postgresql username:

```
  SET ROLE postgres;
+ ERROR:  role "postgres" does not exist
```

Have to create the user with:

```
createuser -s postgres
```

However, this does not seem to set the problem entirely as I get similar failures in addition to a difference in the COLLATE.

https://gist.github.com/rngadam/c31d0f5bac05cd07e3bfbc7796df2371

**Comment by lacanoid** [comment]
I have further modified some of the tests so that they should pass in your environment now.
Class, script and misc should pass now.

Some of the issues with tests still remain. I need to think those over a bit more.

Unfortunately, postgres doesn’t support IF NOT EXISTS for CREATE USER (yet), so you will likely still have to create postgres user yourself, if building as you do.

**Comment by rngadam** [comment]
user exists:

```
> createuser -s postgres
createuser: creation of new role failed: ERROR:  role "postgres" already exists
```

Still some failures:

```
rngadam@rngadam-mac ~/c/p/s/pgddl> make install installcheck
/bin/sh /usr/local/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/share/postgresql/extension'
/bin/sh /usr/local/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/share/postgresql/extension'
/usr/bin/install -c -m 644 .//ddl.control '/usr/local/share/postgresql/extension/'
/usr/bin/install -c -m 644  ddl--0.9.sql '/usr/local/share/postgresql/extension/'
/usr/local/lib/postgresql/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/local/Cellar/postgresql/10.2/bin'    --inputdir=test --dbname=contrib_regression init role type class fdw misc script 
(using postmaster on Unix socket, default port)
============== dropping database "contrib_regression" ==============
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test init                     ... ok
test role                     ... ok
test type                     ... FAILED
test class                    ... ok
test fdw                      ... FAILED
test misc                     ... ok
test script                   ... ok

======================
 2 of 7 tests failed. 
======================
```

diffs output: https://gist.github.com/rngadam/a880a1dba0cc153a06ec0a02a03b383d
