### ISSUE TITLE
Publish on PGXN ?

### ISSUE THREAD

**Issue by daamien** [lacanoid/pgddl#7]
Hi !

Thanks a lot for this project. This is an impressive work.

I see you've done the first step to publish this extension on PGXN but it looks like you did not upload it to the main server. Is there a specific reason for that ? 

I'd like to use pgddl has a dependency of an another extension I am building. Having both extensions available on PGXN would make it easier to install...

Let me know how I can help on this subject.

**Comment by lacanoid** [comment]
I requested a username on PGXN, but got no response, so I wasn't really sure if it is still operational.

I would certainly be interested in making it available.

**Comment by daamien** [comment]
Hi ! 

The service is alive and operationnel. This may be caused by technical issue or lost email or something. I'll contact the PGXN maintainer and see if that helps. When did you try to register and what was the username you picked ?

**Comment by theory** [comment]
Hi. I don't see any requests from you, @lacanoid. Did you fill out [the form](http://manager.pgxn.org/account/register) to request an account? What username did you request?

**Comment by lacanoid** [comment]
I believe I did, but it was some time ago.
Filled it out again just now.

**Comment by theory** [comment]
Approved; were you able to get in? Looks as though [you were](https://pgxn.org/user/Lacanoid).

**Comment by lacanoid** [comment]
Yes, everything works. Thanks!
However, it seems I have to use semantic versioning in META.json.
I will fix this in the next release and upload then.

**Comment by daamien** [comment]
@lacanoid @theory : Thanks to both of you for the quick reply !

I guess you can close this issue.
